### ISSUE TITLE
OpenType shaping parameter

### ISSUE THREAD

**Issue by svgeesus** [svgeesus/ietf-justfont#1]
From Grzegorz Rolek ‏@grzegorzrolek
 https://twitter.com/grzegorzrolek/status/662471907674079232

> @nattokirai @svgeesus BTW, wouldn't OT shaping parameter be better named ‘OTL’? ‘OTF’ is often used vs TTF WRT outline data. @TiroTypeworks

**Comment by grzegorzrolek** [comment]
Yes, the rationale is that ‘OpenType Layout’ is the term used by Microsoft and others to describe text shaping capabilities of OpenType (https://www.microsoft.com/typography/otspec/TTOCHAP1.htm) and ‘OTL’ is a commonly used initialism. It has proved very useful in situations where ‘OTF’ would often be ambiguous.

**Comment by svgeesus** [comment]
Arguments in favour of OTL seem sound. I see no downside to changing it - does anyone else? Suggest we accept the change and close this issue.

**Comment by svgeesus** [comment]
Indeed the introduction says 
      perhaps "TTF", "OTF" or "SFNT" (the names of
      commonly used TrueType and OpenType font formats
which is clearly using OTF as a format not as a layout type. I'm going to commit the change to OTL for this parameter.
