### ISSUE TITLE
Where are @font-face format identifiers defined?

### ISSUE THREAD

**Issue by svgeesus** [svgeesus/ietf-justfont#14]
From Martin J. Dürst duerst@it.aoyama.ac.jp

The start of section 7 introduces @font-face format identifiers. It uses the word "defined" for these, but only talks about the types defined in the document itself. This raises the following questions:
- Are registrations of new subtypes supposed to give this
  information, too? If yes, who is responsible to avoid conflicts?
  (we could just ask IANA to check that the identifier doesn't clash
   with that of another subtype)
- Will a future version of css-fonts-3 reference the IANA registry
  for these values, or how will potential discrepancies be solved?
- If the information in css-fonts-3 is supposed to be normative, and
  the information in the IANA registry just informative, then
  clearly say so in the draft.

**Comment by svgeesus** [comment]
The question of what information new registrations must provide is best solved by abstracting the existing registrations into a registration template. This would include the @font-face format identifier.

I agree that checking for a clash on new registrations is desirable. This can be on the ietf-types list.

Contrary to CSS2 (where the list of anticipated formats was speculative) the list of formats in CSS3 Fonts is based on existing practice and is thus likely to change slowly. Thus, I feel that the normative source should be the individual registrations, and it will be easy to add new ones to CSS3 Fonts via the errata mechanism.

**Comment by wseltzer** [comment]
Does that need clarification in the text? a post on the ml to discuss/confirm?

**Comment by svgeesus** [comment]
It does need clarification in the text. I planned to add a registration template, extending the one in section _5.6.  Registration Template_ of [RFC 6838](https://tools.ietf.org/html/rfc6838) to add the @font-face format field. However, I see that there is now an online form as the preferred submission method:
http://www.iana.org/form/media-types
so perhaps this should be mentioned in the _IANA Considerations_ section.

**Comment by svgeesus** [comment]
Also need to reference the ABNF of section _4.2.  Naming Requirements_ of  [RFC 6838](https://tools.ietf.org/html/rfc6838#section-4.2)

**Comment by svgeesus** [comment]
Related: https://github.com/w3c/csswg-drafts/issues/513

**Comment by svgeesus** [comment]
Looks like CSS 4 Fonts will add a new specifier rather than adding to the format specifier
https://github.com/w3c/csswg-drafts/issues/633
