### ISSUE TITLE
Fragment syntax for collections should be robust against inserting, as well as appending, new fonts to a collection

### ISSUE THREAD

**Issue by svgeesus** [svgeesus/ietf-justfont#18]
From Ken Lunde:

> The latter method will be more reliable, because it doesn't depend on the order of the fonts within the collection, which have the potential to change over time, especially if additional fonts are added. A good real-world example of this is the forthcoming HK (Hong Kong) support for Source Han Sans (Adobe) and Noto Sans CJK (Google) that will add HK versions of the fonts to the collection, both weight-specific and the Super OTCs. These additional fonts will not be appended, but rather inserted, at least for the Super OTCs.
> 
> Come to think of it, this actually happened to the SuperOTCs in Version 1.002 when HW (half-width) fonts were added for Regular and Bold. They were inserted, not appended.

**Comment by svgeesus** [comment]
Further clarification from Ken Lunde:

> In other words, font collections have the potential to change the relative ordering of the fonts, which would usually happen when fonts are added. This is in terms of their index values, and this has actually happened in at least one broadly-distributed collection, and there are plans in place for having this happen again.
> 
> I was told that the 'name' table plays little or no part in terms of how CSS deals with a font collection, which is unfortunate because that is the table which provides the most reliable (unique) name of a font, such as the name.ID=6 string.

**Comment by svgeesus** [comment]
From the OpenType 1.8 specification for the name table:
https://www.microsoft.com/typography/otspec/name.htm

> **6**  
> Postscript name for the font; Name ID 6 specifies a string which is used to invoke a PostScript language font that corresponds to this OpenType font. When translated to ASCII, the name string must be no longer than 63 characters and restricted to the printable ASCII subset, codes 33 – 126, except for the 10 characters '[', ']', '(', ')', '{', '}', '<', '>', '/', '%'.
> 
> In a CFF OpenType font, there is no requirement that this name be the same as the font name in the CFF’s Name INDEX. Thus, the same CFF may be shared among multiple font components in a Font Collection. See the 'name' table section of Recommendations for OpenType fonts "" for additional information.

**Comment by svgeesus** [comment]
The Postscript name is already used in CSS 3 Fonts, in the local() part of the src descriptor
https://drafts.csswg.org/css-fonts/Fonts.html#src-desc
although that discussion does not mention font collections.

However, if the locally installed version for the bold face of  Foo can already be referenced in CSS 3 Fonts using
`src: local(Foo-Bold)`
then it hardly seems a stretch to extend that to point to the bold face of Foo which happens to be in a  collection
`src: local(Foo-Bold)`
and also to point to a non-installed webfont which is a collection, like
`src: url(https://example.org/Bar.woff2#Foo-Bold)`

**Comment by svgeesus** [comment]
It is an open question whether the fragment syntax should allow Postscript names _as well_ as number, or _instead of_ number.

I think it is okay to allow both, as long as the name is searched for first. So if someone happens to have a font family called "7", with a single weight, the ambiguity of #7 is resolved by first searching for a name, then if that fails searching for a number.

On the other hand, just using the Postscript name is clearer and more self-documenting, maybe we don't need the numeric fragments at all?

**Comment by seantek** [comment]
Another possibility is to search for numbers with a reserved character that cannot appear in a name, such as #!7 or #@7 .

**Comment by svgeesus** [comment]
On reflection, the numeric fragment syntax has no obvious benefit. It isn't deployed, and is fragile. Allowing both the numeric version and the string:based (PostScript ID) version requires carfeful disambiguation rules to allow for a font that has a numeric font name.

Removing the numeric fragment and just allowing the PostScript ID seems better. That ID is already used in CSS 3 Fonts when referencing local fonts, for example

src: local(Foo-Bold)

so therefore, if a woff2 holds a collection, it is simple and straightforward to say

src: url(https://example.org/Bar.woff2#Foo-Bold)
rather than
src: url(https://example.org/Bar.woff2#3)

Unless someone speaks out in favor of the numeric fragment syntax, i plan to remove it and add the PostScript name in its place.

**Comment by svgeesus** [comment]
From Ken Lunde:

>  I am all for using the name.ID=6 string for this. Eric Muller once described a font collection in a way that may help. He said that it is simply a packaging detail, and that each font should be treated separately, but that their glyphs happen to come from a shared bucket (the 'glyf' of 'CFF' -- and now 'CFF2' -- table).
