### ISSUE TITLE
Multiple outlines

### ISSUE THREAD

**Issue by svgeesus** [svgeesus/ietf-justfont#2]
> <t>TTF, CFF or SVG outlines can be present in various combinations in the same font file, therefore, multiple values for the same optional parameter may be defined.</t>

How exactly? comma separated list?

**Comment by svgeesus** [comment]
I also find "various combinations" to be needlessly wooly. Is this for forwards compat in case someday CFF and TTF are allowed in the same font file? There are (in OFF v.3) only four valid combinations:
- TTF
- CFF
- TTF, SVG
- CFF, SVG
  It seems clearer to say either TTF or CFF, optionally followed by SVG.

Do I need to give a whole grammar along the lines of
(wsp? comma wsp*) | wsp+
Alternatively, no commas and just whitespace separated (one or more 0x20).

**Comment by vlevantovsky** [comment]
(copy of email sent to justfont mailing list):
Although it is unusual to see TTF and CFF outlines present in the same font file, I don't think it is prohibited by the current OFF specification. While the "version" field" only offers a single choice of values for either TTF or CFF outlines having both types be present is a possibility. I'd suggest that we should say that multiple values of the parameter in question can be defined as a comma-separated list of values without imposing any particular restrictions on what these values can be or how different types of outlines can be combined. Whether there is a valid use case to have only SVG outlines present, or if there is (is not) a use case that combines TTF and CFF outlines shouldn't be decided here, I'd rather allow the parameter to reflect what the font data provides.

**Comment by svgeesus** [comment]
That makes a lot of sense. Okay so comma-separated list, and defer to the OFF spec on allowed combinations.

**Comment by svgeesus** [comment]
The new draft includes the suggested wording from Vlad Levantovsky, a
bit more open-ended than what I had suggested, to allow for future
spec changes. It defers to the OFF spec on allowed combinations rather
than listing those which are currently possible.

Either way, it clarifies that there is no magic number of fonts
containing SVG outlines.

**Comment by svgeesus** [comment]
Seems to be on-list consensus
