### ISSUE TITLE
Magic number for SVG

### ISSUE THREAD

**Issue by svgeesus** [svgeesus/ietf-justfont#3]
>  <t hangText="Magic number(s):">The TrueType fonts and OFF / OpenType fonts containing  TrueType outlines should use 0x00010000 as the 'sfnt' version number.<vspace blankLines="1" />
> <t>The OFF / OpenType fonts containing CFF data should use the tag 'OTTO' as 'sfnt' version number.</t>

Magic number for SVG outlines? More info on allowed combinations (or pointer to it)?

**Comment by rsheeter** [comment]
Would https://www.microsoft.com/typography/otspec/otff.htm suffice? - specifically `OpenType fonts that contain TrueType outlines should use the value of 1.0 for the sfnt version. OpenType fonts containing CFF data should use the tag 'OTTO' as the sfnt version number.`

**Comment by svgeesus** [comment]
And thus, there is no magic number for SVG because it is never present alone, only in combination with either TT or CFF outlines.
